#Breast cancer claasification using logistic regression

  Import all Required Libraries

In [7]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer

Load the Dataset

0 -> Benig which is safe
1 -> malignant which is not safe

In [8]:
data = load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
        1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]),
 'frame': None,
 'target_names': array(['malignant', 'benign'], dtype='<U9'),
 'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 569\n\n:Number of Attributes: 30 numeric, predictive attributes and the class\n\n:Attribute Information:\n    - radius (mean of distances from center to points on the perimeter)\n    - texture (standard deviation of gray-scale values)\n    - perimeter\n    - area\n    - smoothness (local variation in radius lengths)\n    - compactness (perimeter^2 / area - 1.0)\n    - concavity (severity of concave portions of the contour)\n    - concave points (number of concave portions of the contour)\n    - symmetry\n    - fractal dimension ("coastline approximation" - 1)\n\n    The mean, standard error, and "worst" or largest (mean of the three\n    worst/largest values) of these features were computed for each image,\n    resulting in 30 features.  For instance, field 0 is Mean Radius, field\n    10 is Radius SE, field 20 is Worst Radius.\n\n    - class:\n            - WDBC-Malignant\n            - WDBC-Benign\n\n:Summary Statistics:\n\n===================================== ====== ======\n                                        Min    Max\n===================================== ====== ======\nradius (mean):                        6.981  28.11\ntexture (mean):                       9.71   39.28\nperimeter (mean):                     43.79  188.5\narea (mean):                          143.5  2501.0\nsmoothness (mean):                    0.053  0.163\ncompactness (mean):                   0.019  0.345\nconcavity (mean):                     0.0    0.427\nconcave points (mean):                0.0    0.201\nsymmetry (mean):                      0.106  0.304\nfractal dimension (mean):             0.05   0.097\nradius (standard error):              0.112  2.873\ntexture (standard error):             0.36   4.885\nperimeter (standard error):           0.757  21.98\narea (standard error):                6.802  542.2\nsmoothness (standard error):          0.002  0.031\ncompactness (standard error):         0.002  0.135\nconcavity (standard error):           0.0    0.396\nconcave points (standard error):      0.0    0.053\nsymmetry (standard error):            0.008  0.079\nfractal dimension (standard error):   0.001  0.03\nradius (worst):                       7.93   36.04\ntexture (worst):                      12.02  49.54\nperimeter (worst):                    50.41  251.2\narea (worst):                         185.2  4254.0\nsmoothness (worst):                   0.071  0.223\ncompactness (worst):                  0.027  1.058\nconcavity (worst):                    0.0    1.252\nconcave points (worst):               0.0    0.291\nsymmetry (worst):                     0.156  0.664\nfractal dimension (worst):            0.055  0.208\n===================================== ====== ======\n\n:Missing Attribute Values: None\n\n:Class Distribution: 212 - Malignant, 357 - Benign\n\n:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n:Donor: Nick Street\n\n:Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. dropdown:: References\n\n  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction\n    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on\n    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n    San Jose, CA, 1993.\n  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and\n    prognosis via linear programming. Operations Research, 43(4), pages 570-577,\n    July-August 1995.\n  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)\n    163-171.\n',
 'feature_names': array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
        'mean smoothness', 'mean compactness', 'mean concavity',
        'mean concave points', 'mean symmetry', 'mean fractal dimension',
        'radius error', 'texture error', 'perimeter error', 'area error',
        'smoothness error', 'compactness error', 'concavity error',
        'concave points error', 'symmetry error',
        'fractal dimension error', 'worst radius', 'worst texture',
        'worst perimeter', 'worst area', 'worst smoothness',
        'worst compactness', 'worst concavity', 'worst concave points',
        'worst symmetry', 'worst fractal dimension'], dtype='<U23'),
 'filename': 'breast_cancer.csv',
 'data_module': 'sklearn.datasets.data'}

In [9]:
X = pd.DataFrame(data.data , columns = data.feature_names)
y = pd.Series(data.target)

Binary Classification Problem
1. 0 => Malignant
2. 1 => Benign

In [10]:
y.value_counts()

1    357
0    212
Name: count, dtype: int64

In [11]:
X.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

Observation: For 0's it Occupies almost 38% Whereas 1's it Occupies 62%

#Stratify - The Stratify parameter in scikit-learn's train_test_split function ensures that the traning and testing subsets maintain the exact same proportion of class labels as the original dataset

Data Split

In [25]:
from sklearn.model_selection  import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [26]:
X_train.shape

(426, 30)

In [27]:
X_test.shape

(143, 30)

Feature Scaling

In [28]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

Model Traning: Logistic Regression

In [16]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Prediction

In [17]:
y_pred = model.predict(X_test_scaled)
print(y_pred)

[1 1 1 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 1 0 1 0 0 1 1 0 1 0 1 0 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 1 1 0 1 0 0 0 1 0 1 1 1 0 0 0 0 1
 1 1 1 1 1 1 0 0 0 0 0 1 1 0 1 1 1 1 1 0 0 1 1 1 0 1 1 1 1 1 0 0 1 0 1 1 1
 0 1 1 0 1 0 1 1 0 1 1 1 1 0 1 0 1 1 0 0 0 0 0 1 0 1 1 1 0 1 1 1]

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

Model Predicted Probablities

Probablity of class 1 and 0 both

In [30]:
probs_test = model.predict_proba(X_test_scaled)
print(probs_test)

[[0.45489546 0.54510454]
 [0.28607802 0.71392198]
 [0.38973037 0.61026963]
 [0.52139323 0.47860677]
 [0.21418796 0.78581204]
 [0.13743016 0.86256984]
 [0.99143603 0.00856397]
 [0.03138951 0.96861049]
 [0.0706549  0.9293451 ]
 [0.58688546 0.41311454]
 [0.66493246 0.33506754]
 [0.63523455 0.36476545]
 [0.01598516 0.98401484]
 [0.08718667 0.91281333]
 [0.27710873 0.72289127]
 [0.46744749 0.53255251]
 [0.69201587 0.30798413]
 [0.99759467 0.00240533]
 [0.99115226 0.00884774]
 [0.62100626 0.37899374]
 [0.07306042 0.92693958]
 [0.75187552 0.24812448]
 [0.34710805 0.65289195]
 [0.50917903 0.49082097]
 [0.50643252 0.49356748]
 [0.49801112 0.50198888]
 [0.23747647 0.76252353]
 [0.74034105 0.25965895]
 [0.09973947 0.90026053]
 [0.96397721 0.03602279]
 [0.26671091 0.73328909]
 [0.98911247 0.01088753]
 [0.44136089 0.55863911]
 [0.17272191 0.82727809]
 [0.39749518 0.60250482]
 [0.32518809 0.67481191]
 [0.42763473 0.57236527]
 [0.18423983 0.81576017]
 [0.02547665 0.97452335]
 [0.20788947 0.79211053]
 [0.0177457  0.9822543 ]
 [0.44370544 0.55629456]
 [0.01426391 0.98573609]
 [0.29215305 0.70784695]
 [0.14645305 0.85354695]
 [0.97746026 0.02253974]
 [0.30526368 0.69473632]
 [0.10005939 0.89994061]
 [0.02148903 0.97851097]
 [0.41328777 0.58671223]
 [0.1305726  0.8694274 ]
 [0.41143995 0.58856005]
 [0.59889708 0.40110292]
 [0.84405495 0.15594505]
 [0.11526864 0.88473136]
 [0.19656243 0.80343757]
 [0.03511392 0.96488608]
 [0.13015035 0.86984965]
 [0.30373679 0.69626321]
 [0.9765494  0.0234506 ]
 [0.25147455 0.74852545]
 [0.5404844  0.4595156 ]
 [0.95228912 0.04771088]
 [0.54216197 0.45783803]
 [0.20858018 0.79141982]
 [0.51406955 0.48593045]
 [0.089715   0.910285  ]
 [0.32380828 0.67619172]
 [0.0662899  0.9337101 ]
 [0.58566914 0.41433086]
 [0.63465986 0.36534014]
 [0.73060668 0.26939332]
 [0.80260254 0.19739746]
 [0.44067092 0.55932908]
 [0.36693901 0.63306099]
 [0.02052277 0.97947723]
 [0.40273004 0.59726996]
 [0.17705432 0.82294568]
 [0.01211512 0.98788488]
 [0.42444317 0.57555683]
 [0.52499641 0.47500359]
 [0.59013009 0.40986991]
 [0.77990966 0.22009034]
 [0.55792807 0.44207193]
 [0.91980789 0.08019211]
 [0.39859096 0.60140904]
 [0.23737842 0.76262158]
 [0.72882977 0.27117023]
 [0.41781829 0.58218171]
 [0.46393883 0.53606117]
 [0.47470841 0.52529159]
 [0.30577691 0.69422309]
 [0.05208319 0.94791681]
 [0.73820955 0.26179045]
 [0.56354896 0.43645104]
 [0.49936041 0.50063959]
 [0.09043118 0.90956882]
 [0.48668342 0.51331658]
 [0.91388778 0.08611222]
 [0.39663365 0.60336635]
 [0.47100034 0.52899966]
 [0.01101901 0.98898099]
 [0.19100468 0.80899532]
 [0.08066955 0.91933045]
 [0.89858418 0.10141582]
 [0.92804303 0.07195697]
 [0.45361356 0.54638644]
 [0.60799417 0.39200583]
 [0.03383596 0.96616404]
 [0.11973761 0.88026239]
 [0.08547863 0.91452137]
 [0.78146377 0.21853623]
 [0.05255796 0.94744204]
 [0.18158413 0.81841587]
 [0.74047744 0.25952256]
 [0.04092793 0.95907207]
 [0.74880294 0.25119706]
 [0.41087336 0.58912664]
 [0.28898637 0.71101363]
 [0.93432557 0.06567443]
 [0.49569349 0.50430651]
 [0.24423901 0.75576099]
 [0.28860931 0.71139069]
 [0.46758158 0.53241842]
 [0.86982349 0.13017651]
 [0.25434551 0.74565449]
 [0.59642359 0.40357641]
 [0.11529035 0.88470965]
 [0.13148329 0.86851671]
 [0.8080268  0.1919732 ]
 [0.64468624 0.35531376]
 [0.61481625 0.38518375]
 [0.88863775 0.11136225]
 [0.8982102  0.1017898 ]
 [0.12900149 0.87099851]
 [0.66545509 0.33454491]
 [0.13700369 0.86299631]
 [0.11795358 0.88204642]
 [0.11809511 0.88190489]
 [0.74688145 0.25311855]
 [0.33397163 0.66602837]
 [0.39244019 0.60755981]
 [0.14997409 0.85002591]]

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

Probablity of class 1

In [29]:
probs_test = model.predict_proba(X_test_scaled)[: ,1]
print(probs_test)

[0.54510454 0.71392198 0.61026963 0.47860677 0.78581204 0.86256984
 0.00856397 0.96861049 0.9293451  0.41311454 0.33506754 0.36476545
 0.98401484 0.91281333 0.72289127 0.53255251 0.30798413 0.00240533
 0.00884774 0.37899374 0.92693958 0.24812448 0.65289195 0.49082097
 0.49356748 0.50198888 0.76252353 0.25965895 0.90026053 0.03602279
 0.73328909 0.01088753 0.55863911 0.82727809 0.60250482 0.67481191
 0.57236527 0.81576017 0.97452335 0.79211053 0.9822543  0.55629456
 0.98573609 0.70784695 0.85354695 0.02253974 0.69473632 0.89994061
 0.97851097 0.58671223 0.8694274  0.58856005 0.40110292 0.15594505
 0.88473136 0.80343757 0.96488608 0.86984965 0.69626321 0.0234506
 0.74852545 0.4595156  0.04771088 0.45783803 0.79141982 0.48593045
 0.910285   0.67619172 0.9337101  0.41433086 0.36534014 0.26939332
 0.19739746 0.55932908 0.63306099 0.97947723 0.59726996 0.82294568
 0.98788488 0.57555683 0.47500359 0.40986991 0.22009034 0.44207193
 0.08019211 0.60140904 0.76262158 0.27117023 0.58218171 0.53606117
 0.52529159 0.69422309 0.94791681 0.26179045 0.43645104 0.50063959
 0.90956882 0.51331658 0.08611222 0.60336635 0.52899966 0.98898099
 0.80899532 0.91933045 0.10141582 0.07195697 0.54638644 0.39200583
 0.96616404 0.88026239 0.91452137 0.21853623 0.94744204 0.81841587
 0.25952256 0.95907207 0.25119706 0.58912664 0.71101363 0.06567443
 0.50430651 0.75576099 0.71139069 0.53241842 0.13017651 0.74565449
 0.40357641 0.88470965 0.86851671 0.1919732  0.35531376 0.38518375
 0.11136225 0.1017898  0.87099851 0.33454491 0.86299631 0.88204642
 0.88190489 0.25311855 0.66602837 0.60755981 0.85002591]

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

Probablity for class 0

In [19]:
probs_test = model.predict_proba(X_test_scaled)[: ,0]
print(probs_test)

[0.45489546 0.28607802 0.38973037 0.52139323 0.21418796 0.13743016
 0.99143603 0.03138951 0.0706549  0.58688546 0.66493246 0.63523455
 0.01598516 0.08718667 0.27710873 0.46744749 0.69201587 0.99759467
 0.99115226 0.62100626 0.07306042 0.75187552 0.34710805 0.50917903
 0.50643252 0.49801112 0.23747647 0.74034105 0.09973947 0.96397721
 0.26671091 0.98911247 0.44136089 0.17272191 0.39749518 0.32518809
 0.42763473 0.18423983 0.02547665 0.20788947 0.0177457  0.44370544
 0.01426391 0.29215305 0.14645305 0.97746026 0.30526368 0.10005939
 0.02148903 0.41328777 0.1305726  0.41143995 0.59889708 0.84405495
 0.11526864 0.19656243 0.03511392 0.13015035 0.30373679 0.9765494
 0.25147455 0.5404844  0.95228912 0.54216197 0.20858018 0.51406955
 0.089715   0.32380828 0.0662899  0.58566914 0.63465986 0.73060668
 0.80260254 0.44067092 0.36693901 0.02052277 0.40273004 0.17705432
 0.01211512 0.42444317 0.52499641 0.59013009 0.77990966 0.55792807
 0.91980789 0.39859096 0.23737842 0.72882977 0.41781829 0.46393883
 0.47470841 0.30577691 0.05208319 0.73820955 0.56354896 0.49936041
 0.09043118 0.48668342 0.91388778 0.39663365 0.47100034 0.01101901
 0.19100468 0.08066955 0.89858418 0.92804303 0.45361356 0.60799417
 0.03383596 0.11973761 0.08547863 0.78146377 0.05255796 0.18158413
 0.74047744 0.04092793 0.74880294 0.41087336 0.28898637 0.93432557
 0.49569349 0.24423901 0.28860931 0.46758158 0.86982349 0.25434551
 0.59642359 0.11529035 0.13148329 0.8080268  0.64468624 0.61481625
 0.88863775 0.8982102  0.12900149 0.66545509 0.13700369 0.11795358
 0.11809511 0.74688145 0.33397163 0.39244019 0.14997409]

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

Model Evaluation

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[18 35]
 [34 56]]

In [21]:
print("The overall accuracy is: ",accuracy_score(y_test, y_pred))

The overall accuracy is:  0.5174825174825175

In [22]:
print("The precision Valur is " , precision_score(y_test, y_pred))

The precision Valur is  0.6153846153846154

In [23]:
print("The recall value is: " , recall_score(y_test , y_pred))

The recall value is:  0.6222222222222222

In [24]:
print("The f1 score value is: " ,f1_score(y_test, y_pred))

The f1 score value is:  0.6187845303867403