Import all the required libraries

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

Load the data

In [1]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()

In [3]:
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33 (1997) 291-297\n'}

In [4]:
print(housing.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33 (1997) 291-297

In [ ]:
print(housing.feature_names)

['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']

In [ ]:
print(housing.data)

[[   8.3252       41.            6.98412698 ...    2.55555556
    37.88       -122.23      ]
 [   8.3014       21.            6.23813708 ...    2.10984183
    37.86       -122.22      ]
 [   7.2574       52.            8.28813559 ...    2.80225989
    37.85       -122.24      ]
 ...
 [   1.7          17.            5.20554273 ...    2.3256351
    39.43       -121.22      ]
 [   1.8672       18.            5.32951289 ...    2.12320917
    39.43       -121.32      ]
 [   2.3886       16.            5.25471698 ...    2.61698113
    39.37       -121.24      ]]

In [ ]:
type(housing)

sklearn.utils._bunch.Bunch

In [ ]:
dataset = pd.DataFrame(housing.data, columns = housing.feature_names)
dataset

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

Perform EDA

In [ ]:
dataset['Price'] = housing.target
dataset.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [ ]:
dataset.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
Price         0
dtype: int64

Data split into independent feature and target feature

In [ ]:
X = dataset.iloc[:, :-1]
y = dataset.iloc[: , -1]

In [ ]:
X

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [ ]:
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: Price, Length: 20640, dtype: float64

Train&Test split

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=44)

Data Standardization

In [ ]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScalar()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
5567,2.6618,19.0,4.666667,1.142132,2047.0,3.463621,33.88,-118.28
3116,3.9261,12.0,5.657303,1.044944,1027.0,2.884831,35.63,-117.76
4750,2.5320,39.0,3.734257,1.022670,2638.0,3.322418,34.04,-118.32
13963,3.9688,15.0,16.550562,3.078652,622.0,2.329588,34.24,-116.87
2262,1.9575,24.0,4.528424,1.058140,2098.0,2.710594,36.79,-119.83
...,...,...,...,...,...,...,...,...
18528,3.2437,44.0,4.996139,1.038610,645.0,2.490347,36.96,-122.04
20355,1.9811,16.0,6.104730,1.168919,587.0,1.983108,34.19,-118.96
16955,6.0000,40.0,5.990196,1.006536,751.0,2.454248,37.53,-122.30
3491,5.1408,33.0,5.359862,0.913495,881.0,3.048443,34.27,-118.47
14100,1.5517,31.0,3.110831,0.974811,816.0,2.055416,32.76,-117.09

In [ ]:
X_test

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
20127,4.4219,34.0,5.850220,1.074890,795.0,3.502203,34.40,-118.98
18256,6.1995,36.0,6.309756,1.014634,1055.0,2.573171,37.38,-122.09
10376,10.1531,2.0,9.906329,1.130380,2985.0,3.778481,33.64,-117.62
4109,6.5533,34.0,6.431154,1.086231,1572.0,2.186370,34.14,-118.39
8169,5.0447,36.0,5.953020,1.003356,784.0,2.630872,33.81,-118.12
...,...,...,...,...,...,...,...,...
2312,3.9032,3.0,5.863330,1.192913,4432.0,2.492688,36.85,-119.74
18574,2.5599,42.0,2.826446,0.966942,2312.0,4.776860,36.91,-121.75
14552,6.4696,10.0,7.217391,0.971014,1700.0,3.519669,32.97,-117.13
1430,4.6375,28.0,6.281780,1.129237,1591.0,3.370763,38.00,-122.02
4977,2.1354,44.0,4.613158,1.018421,1165.0,3.065789,34.00,-118.29

Model Training: Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression
model_linear_regression = LinearRegression()
model_linear_regression.fit(X_train , y_train)

LinearRegression()

Display the coefficients and intercept

In [ ]:
print(f'The linear regression model coefficients are:{model_linear_regression.coef_} ')
print(f'The linear regression model  intercept is:{model_linear_regression.intercept_} ')

The linear regression model coefficients are:[ 4.37601077e-01  9.18748723e-03 -1.08606741e-01  7.22281757e-01
 -1.01380633e-06 -3.44095456e-03 -4.24327264e-01 -4.36447999e-01]
The linear regression model  intercept is:-37.14903811779413

In [ ]:
y_cap_linear_regression = model_linear_regression.predict(X_test)
print(y_cap_linear_regression)

[2.55823281 3.35684836 4.09751962 ... 2.80867915 2.38870762 1.61280809]

In [ ]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test, y_cap_linear_regression))

0.5347838950335057

In [ ]:
from sklearn.metrics import r2_score
print(r2_score(y_test, y_cap_linear_regression))

0.6084415600235549

Lasso Regression[L1 regression]

In [ ]:
from sklearn.linear_model import Lasso
model_lasso_regression = Lasso()
model_lasso_regression.fit(X_train , y_train)

Lasso()

In [ ]:
print(f'The lasso regression model coefficients are: {model_linear_regression.coef_}')
print(f'The lasso regression model intercept are: {model_linear_regression.intercept_}')

The lasso regression model coefficients are: [ 1.43690485e-01  5.20358452e-03  0.00000000e+00 -0.00000000e+00
 -5.55851727e-06 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00]
The lasso regression model intercept are: 1.3693984377784125

In [ ]:
y_cap_lasso_regression = model_lasso_regression.predict(X_test)
print(y_cap_lasso_regression)

[2.17728625 2.44167241 2.8221173  ... 2.34160477 2.17261983 1.89871715]

In [ ]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test , y_cap_lasso_regression))

0.9820321744083038

In [ ]:
from sklearn.metrics import r2_score
print(r2_score(y_test , y_cap_lasso_regression))

0.2809750073085123

Ridge Regularization[L2 Regularization]

In [ ]:
from sklearn.linear_model import Ridge
model_ridge_regression = Ridge()
model_ridge_regression.fit(X_train , y_train)

Ridge()

In [ ]:
print(f'The Ridge regression model coefficients are: {model_ridge_regression.coef_}')
print(f'The Ridge regression model intercept are: {model_ridge_regression.intercept_}')

The Ridge regression model coefficients are: [ 4.37450510e-01  9.18931335e-03 -1.08321911e-01  7.20677858e-01
 -1.00850185e-06 -3.44061371e-03 -4.24313734e-01 -4.36414540e-01]
The Ridge regression model intercept are: -37.14478583233588

In [ ]:
y_cap_ridge_regression = model_ridge_regression.predict(X_test)
print(y_cap_ridge_regression)

[2.55831349 3.3568299  4.09779217 ... 2.80901107 2.38873181 1.61300901]

In [ ]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test , y_cap_ridge_regression))

0.5347309733861106

In [ ]:
from sklearn.metrics import r2_score
print(r2_score(y_test, y_cap_ridge_regression))

0.6084803082317329

Obsevation: Ridge regression and Linear regression have similar performance . on the other hand ,Lasso regression have already bad performance over all

Elastic Net Regression

In [ ]:
from sklearn.linear_model import ElasticNet
model_elastic_net = ElasticNet()

In [ ]:
model_elastic_net.fit(X_train , y_train)

ElasticNet()

In [ ]:
print(f'The elastic net regression model coefficients are: {model_elastic_net.coef_}')
print(f'The elastic net regression model intercept are: {model_elastic_net.intercept_}')

The elastic net regression model coefficients are: [ 2.51431246e-01  1.07034964e-02  0.00000000e+00 -0.00000000e+00
  1.04720931e-05 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00]
The elastic net regression model intercept are: 0.7712039551597558

In [ ]:
y_cap_elasticnet_regression = model_elastic_net.predict(X_test)
print(y_cap_elasticnet_regression)

[2.25525197 2.7263259  3.37667673 ... 2.52270107 2.25357536 1.79126407]

In [ ]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test, y_cap_elasticnet_regression))

0.7885008869040337

In [ ]:
from sklearn.metrics import r2_score
print(r2_score(y_test, y_cap_elasticnet_regression))

0.422674878463116

Overall Perormance Comparision
Ridge = linear Regression>Elasticnet>Lasso

Test Multiple Alpha /Lambda Values for ridge , lasso and elastic limit

In [ ]:
alpha_values = [0.01, 0.1, 1, 10]
results = []
for alpha in alpha_values:

  lasso =